import fs from 'fs'
import matter from 'gray-matter'
import { GetStaticProps } from 'next'
import Link from 'next/link'
import path from 'path'
import Layout from '../components/Layout'
import { postFilePaths, POSTS_PATH } from '../utils/mdxUtils'

type Props = {
  posts: {
    frontMatter: { title: string; description?: string }
    filePath: string
  }[]
}

export default function Index({ posts }: Props) {
  return (
    <Layout>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{' '}
        <code>mdx-bundler</code>.
      </p>
      <ul>
        {posts.map((post) => {
          const slug = post.filePath.replace(/\.mdx?$/, '')

          return (
            <li key={post.filePath}>
              <Link as={`/posts/${slug}`} href={`/posts/[slug]`}>
                <a>{post.frontMatter.title}</a>
              </Link>
            </li>
          )
        })}
      </ul>
    </Layout>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const posts = postFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(POSTS_PATH, filePath))
    console.log(source)
    const { data } = matter(source)

    return {
      frontMatter: data,
      filePath
    }
  })

  return { props: { posts } }
}
