import fs from 'fs'
import { bundleMDX } from 'mdx-bundler'
import { GetStaticProps } from 'next'
import Link from 'next/link'
import path from 'path'
import Layout from '../components/Layout'
import { postFilePaths, POSTS_PATH } from '../utils/mdxUtils'

type Props = {
  posts: {
    frontmatter: { title: string; description?: string }
    filePath: string
  }[]
}

export default function Index({ posts }: Props) {
  return (
    <Layout>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{' '}
        <code>mdx-bundler</code>.
      </p>
      <ul>
        {posts.map((post) => {
          const slug = post.filePath.replace(/\.mdx?$/, '')

          return (
            <li key={post.filePath}>
              <Link as={`/posts/${slug}`} href={`/posts/[slug]`}>
                <a>{post.frontmatter.title}</a>
              </Link>
            </li>
          )
        })}
      </ul>
    </Layout>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const posts = await Promise.all(
    postFilePaths.map(async (filePath) => {
      const source = fs.readFileSync(path.join(POSTS_PATH, filePath), 'utf-8')
      const { frontmatter } = await bundleMDX(source)
      return {
        frontmatter,
        filePath
      }
    })
  )

  return { props: { posts } }
}
